export const menuArray = [
  {
    name: "Pizza",
    ingredients: ["pepperoni", "mushroom", "mozarella"],
    id: "pizza",
    price: 14,
    emoji: "🍕",
  },
  {
    name: "Cheeseburger",
    ingredients: ["beef patty", "cheddar", "lettuce", "tomato", "onion"],
    price: 12,
    emoji: "🍔",
    id: "cheeseburger",
  },
  {
    name: "Double Bypass Burger",
    ingredients: ["two beef patties", "bacon", "four cheeses", "special sauce"],
    price: 18,
    emoji: "🍔🍔",
    id: "double-bypass-burger",
  },
  {
    name: "Veggie Burger",
    ingredients: ["plant-based patty", "lettuce", "tomato", "pickle", "avocado"],
    price: 13,
    emoji: "🥗🍔",
    id: "veggie-burger",
  },
  {
    name: "Fries",
    ingredients: ["potatoes", "salt"],
    price: 4,
    emoji: "🍟",
    id: "fries",
  },
  {
    name: "Onion Rings",
    ingredients: ["onions", "batter"],
    price: 5,
    emoji: "🧅",
    id: "onion-rings",
  },
  {
    name: "Cola",
    ingredients: ["carbonated water", "high fructose corn syrup", "caramel color"],
    price: 3,
    emoji: "🥤",
    id: "cola",
  },
  {
    name: "Lemonade",
    ingredients: ["lemons", "sugar", "water"],
    price: 4,
    emoji: "🍋",
    id: "lemonade",
  },
  {
    name: "Milkshake",
    ingredients: ["milk", "ice cream", "flavoring"],
    price: 6,
    emoji: "🥛",
    id: "milkshake",
  },
  {
    name: "Coffee",
    ingredients: ["brewed coffee beans"],
    price: 4,
    emoji: "☕",
    id: "coffee",
  },
  {
    name: "Tea",
    ingredients: ["tea leaves", "hot water"],
    price: 3,
    emoji: "🍵",
    id: "tea",
  },
  {
    name: "Beer",
    ingredients: ["grain", "hops", "yeast", "water"],
    price: 12,
    emoji: "🍺",
    id: "beer",
  },
];
